### ISSUE TITLE
issue on Extending the iOS App for Azure AD Authentication

### ISSUE THREAD

**Issue by nileshj29** [microsoftgraph/msgraph-training-ios-objectivec#11]
I am able to install the microsoft authentication library for my iOS project via CocoaPods.
In My AuthenticationManager class when i declare the following
//public members
@property (nonatomic, strong) MSALUser *user;
I am getting the following error messages:
1)Property with 'retain (or strong)' attribute must be of object type
2)Unknown type name 'MSALUser

any idea why it happening?does installed MSAL  is updated or not?

**Comment by jasonjoh** [comment]
Closing this issue as the project has been overhauled and this code isn't present any more. You likely were hitting the error because of a breaking change in MSAL. `MSALUser` is no longer an object in that library, they use `MSALAccount` now. See https://github.com/microsoftgraph/msgraph-training-ios-objectivec/blob/3b03012c908862faf935148fc14460d31a26d6e1/demos/03-add-msgraph/GraphTutorial/GraphTutorial/AuthenticationManager.m#L79
